name: API Automated Testing

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Installation of Nodejs 
      - name: Use Nodejs 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          
      # Logs user into VirtServer and stores a token that will be used for authentication
      - name: Login to VirtServer
        run: ./virtserver-cli -login -s 18.224.146.21:9090 -u adrian -pw Google1234
        
      # Starts virtual services with the specified tag
      - name: Run Virtual Service
        run: ./virtserver-cli -startwt "TE" -s 18.224.146.21:9090
       
      
        
        
